services:
  app:
    build:
      context: .
    container_name: symfony_app
    ports:
      - "80:8000"
    restart: always 
    volumes:
      - .:/app
      - /app/vendor  # Duy trì mã nguồn trên container
    environment:
      - SYMFONY_ENV=dev
    networks:
      - symfony_network