services:
  app:
    build:
      context: .
    container_name: symfony_app
    ports:
      - "8000:8000"  # Port của ứng dụng Symfony
    volumes:
      - .:/app
    networks:
      - symfony_network
    environment:
        DATABASE_URL: mysql://root:root@db:3306/demo_database