services:
  app:
    build:
      context: .
    container_name: symfony_app
    ports:
      - "80:8000"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/vendor  # Duy trì mã nguồn trên container
    networks:
      - symfony_network
    environment:
        APP_ENV: prod