services:
  db:
    image: mysql:8
    container_name: symfony_db
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    command: [
      "--innodb-buffer-pool-size=32M",
      "--innodb-log-buffer-size=4M",
      "--innodb-redo-log-capacity=32M",
      "--innodb-buffer-pool-instances=1",
      "--max-connections=10",
      "--table-open-cache=64",
      "--thread-cache-size=4",
      "--performance-schema=0",
      "--tmp-table-size=8M",
      "--max-heap-table-size=8M",
    ]

    networks:
      - symfony_network
    restart: unless-stopped

  memcached:
    image: memcached:1.6
    container_name: symfony_memcached
    ports:
      - "11211:11211"
    restart: unless-stopped

volumes:
  db_data: {}

networks:
  symfony_network:
    driver: bridge
