version: '3.8'

services:
  db:
    image: mysql:8
    container_name: symfony_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    command: [
      "--innodb-buffer-pool-size=64M",
      "--innodb-log-buffer-size=8M",
      "--innodb-redo-log-capacity=64M",
      "--innodb-buffer-pool-instances=1",
      "--max-connections=20",
      "--table-open-cache=200",
      "--thread-cache-size=8",
      "--performance-schema=0",
      "--tmp-table-size=16M",
      "--max-heap-table-size=16M",
      "--sort-buffer-size=256K",
      "--join-buffer-size=256K",
      "--read-buffer-size=256K",
      "--read-rnd-buffer-size=512K"
    ]

    networks:
      - symfony_network
    restart: unless-stopped

  memcached:
    image: memcached:1.6
    container_name: symfony_memcached
    ports:
      - "11211:11211"
    restart: unless-stopped

volumes:
  db_data: {}

networks:
  symfony_network:
    driver: bridge
